server:
  port: 8004
spring:
  application:
    name: sc-order-provider

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8811/eureka/
    lease:
      duration: 5
