server:
  port: 8001

spring:
  application:
    name: sc-application-provider

eureka:
  instance:
    hostname: localhost
  client:
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8811/eureka/
    lease:
      duration: 5

feign:
  hystrix:
    enabled: true
