server:
  port: 8001
spring:
  application:
    name: sc-application-provider

eureka:
  instance:
    nonSecurePort: ${server.port:8083}
    leaseRenewalIntervalInSeconds: 5
    leaseExpirationDurationInSeconds: 10
    preferIpAddress: true
    instance-id: ${spring.cloud.client.ipAddress}:${server.port}
    hostname: localhost
  client:
    healthcheck:
      enabled: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:8811/eureka/
    lease:
      duration: 5
